#aurora:
#  APP_KEY: a49a17b8f9a385502205144c
#  MASTER_SECRET: 6bb2f5e0a4244af02b6ec7f1
#
## 需要与前面 Apollo 中创建项目的appId保持一致
app:
#  id: sofa-config-apollo
  id: kamo-cloud-payment
  # 设置 apollo meta service 的地址，因为前面meta和config是部署在一起的，所以就是configService的地址
apollo:
  meta: http://192.168.2.38:8099
  # 配置项
sofa:
  alipay:
    glmapper:
      name: glmapper

kamo:
  cloud:
    paypass: JD_PAY
spring:
  main:
   allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册




